esphome:
  name: hws
  friendly_name: hws

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "<snip>"

ota:
  - platform: esphome
    password: "<snip>"

wifi:
  ssid: !secret wifi_ssid_2
  password: !secret wifi_password_2


uart:
   id: uart_bus
   baud_rate: 9600
   tx_pin: GPIO6
   rx_pin: GPIO5

external_components:
  - source: github://oxan/esphome-stream-server
stream_server:
  uart_id: uart_bus
  port: 6638
